### ISSUE TITLE
AttributeError: module 'cv2.cv2' has no attribute 'cudacodec'

### ISSUE THREAD

**Issue by HoangTienDuc** [cudawarped/opencv-experiments#1]
Hello. your work is so awesome. But i cannot invoke cudacodec. How did you install and run opencv410x-video-read.ipynb

##### System information (version)

- OpenCV == 4.2.0.34
- Operating System / Platform == ubuntu 18.04
- Miniconda-python 3.7

##### Detailed description
Reading video (1920x1080) from RSTP is delayed (2000-3000ms). so i decide to use opencv + gpu.

**Comment by cudawarped** [comment]
Hi, did you build with CUDA and install Nvidia Video Codec SDK?  If not see part 5) from [Accelerate OpenCV 4.4.0 – build with CUDA and python bindings](https://jamesbowley.co.uk/accelerate-opencv-4-4-0-build-with-cuda-and-python-bindings/#prerequisites), from memory the procedure for linux is slightly different however the Nvidia readme covers every detail of what you need to do.

**Comment by tienduchoang** [comment]
Do you have any clear installation documents for ubuntu 18.04? I tried to install it many times but it failed

**Comment by cudawarped** [comment]
Sorry I haven't built on ubuntu for at least 6 months.  Are you trying to build OpenCV or the Nvidia samples.  I would refer to a linux guide like [this one](https://www.pyimagesearch.com/2020/02/03/how-to-use-opencvs-dnn-module-with-nvidia-gpus-cuda-and-cudnn/) to see if you can build OpenCV with the CUDA backend.  Once successful I would try to include ncuvid in the build with
`DWITH_NVCUVID=ON`

**Comment by ichu-lsa** [comment]
I've installed opencv 4.2 with cuda 10.0 and cudnn 7.6.4 on a lot of ubuntu 18.04 computers. I normally just follow pyimagesearch's instructions for doing this: 
https://www.pyimagesearch.com/2020/02/03/how-to-use-opencvs-dnn-module-with-nvidia-gpus-cuda-and-cudnn/ 
and everything works. Make sure you pay attention to each step, copy/paste the instructions that don't have specific filepaths in them and tab complete the ones that do to make sure there are no typos.
